# Generated by Django 2.1.1 on 2018-09-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOf',
            fields=[
                ('significance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Significance')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
            ],
            bases=('base.significance',),
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('significance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Significance')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('base.significance',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('who_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='who.Who')),
            ],
            bases=('who.who',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('who_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='who.Who')),
                ('dateOfBirth', models.DateField()),
                ('dateOfDeath', models.DateField()),
            ],
            bases=('who.who',),
        ),
        migrations.AddField(
            model_name='who',
            name='memberOf',
            field=models.ManyToManyField(to='who.MemberOf'),
        ),
        migrations.AddField(
            model_name='memberof',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberMemberOf', to='who.Who'),
        ),
        migrations.AddField(
            model_name='memberof',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofMemberOf', to='who.Group'),
        ),
    ]
